site_name: "Concursos DCX/CCAE/UFPB"
docs_dir: "docs"
theme:
  name: ivory
  logo: images/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: white
      accent: white
      media: "(prefers-color-scheme: light)"

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light black
      accent: deep orange
      media: "(prefers-color-scheme: dark)"

  footer:
    logo: images/logo.png
    text: "© 2025 Departamento de Ciências Exatas. Todos os direitos reservados."
plugins:
  - search
  - mermaid2
  - awesome-pages
markdown_extensions:
  - codehilite
extra_javascript:
  - js/google-analytics.js
