name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # ou 'master', se for o nome da sua branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.2

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-ivory
          pip install mkdocs-mermaid2-plugin mkdocs-awesome-pages-plugin

      - name: Build site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.RODRIGOR_SECRET }}
          publish_dir: ./site